// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sns

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/sns"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPublishAPI creates a new instance of MockPublishAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPublishAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPublishAPI {
	mock := &MockPublishAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPublishAPI is an autogenerated mock type for the PublishAPI type
type MockPublishAPI struct {
	mock.Mock
}

type MockPublishAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPublishAPI) EXPECT() *MockPublishAPI_Expecter {
	return &MockPublishAPI_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function for the type MockPublishAPI
func (_mock *MockPublishAPI) Publish(ctx context.Context, params *sns.PublishInput, optFns ...func(*sns.Options)) (*sns.PublishOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 *sns.PublishOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sns.PublishInput, ...func(*sns.Options)) (*sns.PublishOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sns.PublishInput, ...func(*sns.Options)) *sns.PublishOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sns.PublishOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sns.PublishInput, ...func(*sns.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPublishAPI_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockPublishAPI_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx
//   - params
//   - optFns
func (_e *MockPublishAPI_Expecter) Publish(ctx interface{}, params interface{}, optFns ...interface{}) *MockPublishAPI_Publish_Call {
	return &MockPublishAPI_Publish_Call{Call: _e.mock.On("Publish",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockPublishAPI_Publish_Call) Run(run func(ctx context.Context, params *sns.PublishInput, optFns ...func(*sns.Options))) *MockPublishAPI_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]func(*sns.Options))
		run(args[0].(context.Context), args[1].(*sns.PublishInput), variadicArgs...)
	})
	return _c
}

func (_c *MockPublishAPI_Publish_Call) Return(publishOutput *sns.PublishOutput, err error) *MockPublishAPI_Publish_Call {
	_c.Call.Return(publishOutput, err)
	return _c
}

func (_c *MockPublishAPI_Publish_Call) RunAndReturn(run func(ctx context.Context, params *sns.PublishInput, optFns ...func(*sns.Options)) (*sns.PublishOutput, error)) *MockPublishAPI_Publish_Call {
	_c.Call.Return(run)
	return _c
}
