packages:
  aws-testing-cookbook/s3:
    interfaces:
      GetObjectAPI:
  aws-testing-cookbook/sqs:
    interfaces:
      ReceiveMessageAPI:
  aws-testing-cookbook/ec2:
    interfaces:
      DescribeInstancesAPI: