// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sqs

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/sqs"
	mock "github.com/stretchr/testify/mock"
)

// NewMockReceiveMessageAPI creates a new instance of MockReceiveMessageAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReceiveMessageAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReceiveMessageAPI {
	mock := &MockReceiveMessageAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReceiveMessageAPI is an autogenerated mock type for the ReceiveMessageAPI type
type MockReceiveMessageAPI struct {
	mock.Mock
}

type MockReceiveMessageAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReceiveMessageAPI) EXPECT() *MockReceiveMessageAPI_Expecter {
	return &MockReceiveMessageAPI_Expecter{mock: &_m.Mock}
}

// ReceiveMessage provides a mock function for the type MockReceiveMessageAPI
func (_mock *MockReceiveMessageAPI) ReceiveMessage(ctx context.Context, params *sqs.ReceiveMessageInput, optFns ...func(*sqs.Options)) (*sqs.ReceiveMessageOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ReceiveMessage")
	}

	var r0 *sqs.ReceiveMessageOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.ReceiveMessageInput, ...func(*sqs.Options)) (*sqs.ReceiveMessageOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.ReceiveMessageInput, ...func(*sqs.Options)) *sqs.ReceiveMessageOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqs.ReceiveMessageOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sqs.ReceiveMessageInput, ...func(*sqs.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReceiveMessageAPI_ReceiveMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReceiveMessage'
type MockReceiveMessageAPI_ReceiveMessage_Call struct {
	*mock.Call
}

// ReceiveMessage is a helper method to define mock.On call
//   - ctx
//   - params
//   - optFns
func (_e *MockReceiveMessageAPI_Expecter) ReceiveMessage(ctx interface{}, params interface{}, optFns ...interface{}) *MockReceiveMessageAPI_ReceiveMessage_Call {
	return &MockReceiveMessageAPI_ReceiveMessage_Call{Call: _e.mock.On("ReceiveMessage",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockReceiveMessageAPI_ReceiveMessage_Call) Run(run func(ctx context.Context, params *sqs.ReceiveMessageInput, optFns ...func(*sqs.Options))) *MockReceiveMessageAPI_ReceiveMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]func(*sqs.Options))
		run(args[0].(context.Context), args[1].(*sqs.ReceiveMessageInput), variadicArgs...)
	})
	return _c
}

func (_c *MockReceiveMessageAPI_ReceiveMessage_Call) Return(receiveMessageOutput *sqs.ReceiveMessageOutput, err error) *MockReceiveMessageAPI_ReceiveMessage_Call {
	_c.Call.Return(receiveMessageOutput, err)
	return _c
}

func (_c *MockReceiveMessageAPI_ReceiveMessage_Call) RunAndReturn(run func(ctx context.Context, params *sqs.ReceiveMessageInput, optFns ...func(*sqs.Options)) (*sqs.ReceiveMessageOutput, error)) *MockReceiveMessageAPI_ReceiveMessage_Call {
	_c.Call.Return(run)
	return _c
}
