// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package s3

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/s3"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGetObjectAPI creates a new instance of MockGetObjectAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetObjectAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetObjectAPI {
	mock := &MockGetObjectAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGetObjectAPI is an autogenerated mock type for the GetObjectAPI type
type MockGetObjectAPI struct {
	mock.Mock
}

type MockGetObjectAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetObjectAPI) EXPECT() *MockGetObjectAPI_Expecter {
	return &MockGetObjectAPI_Expecter{mock: &_m.Mock}
}

// GetObject provides a mock function for the type MockGetObjectAPI
func (_mock *MockGetObjectAPI) GetObject(ctx context.Context, params *s3.GetObjectInput, optFns ...func(*s3.Options)) (*s3.GetObjectOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetObject")
	}

	var r0 *s3.GetObjectOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.GetObjectInput, ...func(*s3.Options)) (*s3.GetObjectOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.GetObjectInput, ...func(*s3.Options)) *s3.GetObjectOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.GetObjectOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.GetObjectInput, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGetObjectAPI_GetObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObject'
type MockGetObjectAPI_GetObject_Call struct {
	*mock.Call
}

// GetObject is a helper method to define mock.On call
//   - ctx
//   - params
//   - optFns
func (_e *MockGetObjectAPI_Expecter) GetObject(ctx interface{}, params interface{}, optFns ...interface{}) *MockGetObjectAPI_GetObject_Call {
	return &MockGetObjectAPI_GetObject_Call{Call: _e.mock.On("GetObject",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockGetObjectAPI_GetObject_Call) Run(run func(ctx context.Context, params *s3.GetObjectInput, optFns ...func(*s3.Options))) *MockGetObjectAPI_GetObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]func(*s3.Options))
		run(args[0].(context.Context), args[1].(*s3.GetObjectInput), variadicArgs...)
	})
	return _c
}

func (_c *MockGetObjectAPI_GetObject_Call) Return(getObjectOutput *s3.GetObjectOutput, err error) *MockGetObjectAPI_GetObject_Call {
	_c.Call.Return(getObjectOutput, err)
	return _c
}

func (_c *MockGetObjectAPI_GetObject_Call) RunAndReturn(run func(ctx context.Context, params *s3.GetObjectInput, optFns ...func(*s3.Options)) (*s3.GetObjectOutput, error)) *MockGetObjectAPI_GetObject_Call {
	_c.Call.Return(run)
	return _c
}
